import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';
import { appName } from '@/lib/shared';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: `The terms that govern your use of ${appName}.`,
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 6, 2026">
      <p>
        By creating an account or using {appName} (the &quot;Service&quot;), you agree to these Terms of Service. If you
        don&apos;t agree, don&apos;t use the Service.
      </p>

      <h2>The Service</h2>
      <p>
        {appName} is an AI-assisted portfolio management tool. It syncs and displays your portfolio data, offers an AI
        Council of AI portfolio-manager personas for research and debate, and — on account tiers that enable it — can
        place trades through a brokerage account you connect (via Alpaca), subject to safeguards you configure:
        dry-run/paper mode by default, an owner-controlled kill switch, and deterministic risk limits.
      </p>

      <h2>Not financial advice</h2>
      <p>
        Nothing in the Service, including anything generated by the AI Council or an automated trading feature, is
        financial, investment, tax, or legal advice. AI-generated analysis can be wrong, out of date, or based on
        incomplete data. You are solely responsible for your investment and trading decisions, and for any losses that
        result from them.
      </p>

      <h2>Accounts</h2>
      <p>
        You must provide accurate information and are responsible for keeping your credentials secure. During the
        current development period, access is limited to an approved email domain allowlist; this restriction may change
        as the Service matures.
      </p>

      <h2>Automated trading</h2>
      <p>
        If you enable automated trade execution (an Ultimate-tier feature), you are explicitly authorizing the Service
        to place orders through your connected Alpaca brokerage account, within the limits and safeguards you configure.
        You can disable this at any time via the in-app kill switch. Enabling live (non-paper) trading means real money
        moves as a direct result of your own configuration — prove out any strategy in paper mode first.
      </p>

      <h2>Subscriptions & billing</h2>
      <p>
        Paid tiers (Pro, Ultimate) are billed monthly in advance through Stripe. You can cancel at any time from your
        account&apos;s billing page; access continues through the end of the current billing period. We don&apos;t offer
        prorated refunds for partial months except where required by law.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Don&apos;t use the Service to violate any law, attempt to access another user&apos;s data, or interfere with the
        Service&apos;s operation.
      </p>

      <h2>Availability & changes</h2>
      <p>
        The Service is under active development and may change — including features, pricing, and these Terms — with
        notice where practical. We aim for reliability but don&apos;t guarantee uninterrupted availability.
      </p>

      <h2>Disclaimer & limitation of liability</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by
        law, we are not liable for indirect, incidental, or consequential damages, including trading losses, arising
        from your use of the Service.
      </p>

      <h2>Termination</h2>
      <p>
        We may suspend or terminate access for violation of these Terms. You may stop using the Service and close your
        account at any time.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms: <a href="mailto:support@dataconnector-pro.com">support@dataconnector-pro.com</a>.
      </p>
    </LegalPage>
  );
}
